/**
 * How often an edit is refused as „couldn't be joined into one line”
 * (`editBrokenLine`), and why: each edit routed exactly as the page routes it
 * (`planEdit` → `/api/reroute-leg` → `applyRuns` → `spliceIsSound`, then the
 * whole-span retry `spanRun`), on real rides generated by the running app.
 *
 * `npx tsx scripts/measure-edit-joins.ts http://localhost:3180 <cache-dir>`
 *
 * Rides are generated once and cached as JSON in <cache-dir>.
 *
 * Measured 2026-09-28 on three rides (Ķemeri → Kaņieris → Ragaciems loop,
 * Sigulda → Līgatne → Cēsis, Mālpils → Mūrnieki → Allaži loop), 24 edits
 * each (`SWEEP=15`), production BRouter, before → after `meetRuns` and
 * `offRoadMeters`:
 *   first splice broken          9 / 72 → 4 / 72
 *   refused as a broken line     2 / 72 → 0 / 72 (both were pins ~600 m
 *                                         from any road, now said as such)
 *   whole-span retry shortening the ride by 10–36 km   4 → 1
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { haversineMeters, type Point } from "../lib/geo/geometry";
import { cumulative, pointAtDistance } from "../lib/routing/detour";
import {
  anchorsOf, applyRuns, applyShapeEdit, coordinatesOf, insertStopsByAlong, lineBreaks, nearestAlong, placesFromRide,
  planEdit, planWithPlaces, shapeFlags, snapToLine, spanRun, spliceIsSound, stopsOf, type EditRun, type RidePlaces, type RoutedRun,
} from "../lib/routing/reroute-leg";
import { composeRidePlan } from "../lib/chat/compose-plan";
import { DEFAULT_PROFILE } from "../lib/chat/ride-profile";
import type { RidePlan } from "../lib/chat/ride-plan";
import type { GenerateRouteResponse, GeneratedRoute } from "../lib/types";

const BASE = process.argv[2] ?? "http://localhost:3180";
const CACHE = process.argv[3] ?? "/tmp/mopik-rides";
const TOL = 500;
const SWEEP = Number(process.env.SWEEP ?? 12);
type Segs = GeneratedRoute["segments"];

type RideSpec = { id: string; trip: "one_way" | "round_trip"; places: { name: string; lat: number; lon: number }[] };
const RIDES: RideSpec[] = [
  { id: "kanieris", trip: "round_trip", places: [
    { name: "Ķemeri", lat: 56.950739, lon: 23.489669 },
    { name: "Kaņieris", lat: 56.996006, lon: 23.472571 },
    { name: "Ragaciems", lat: 57.0333, lon: 23.4925 },
  ] },
  { id: "sigulda", trip: "one_way", places: [
    { name: "Sigulda", lat: 57.1537, lon: 24.8531 },
    { name: "Līgatne", lat: 57.2336, lon: 25.0410 },
    { name: "Cēsis", lat: 57.3119, lon: 25.2707 },
  ] },
  { id: "malpils", trip: "round_trip", places: [
    { name: "Mālpils", lat: 57.0096, lon: 24.9497 },
    { name: "Mūrnieki", lat: 57.092128, lon: 24.927989 },
    { name: "Allaži", lat: 57.1008, lon: 24.8275 },
  ] },
];

async function ride(spec: RideSpec): Promise<{ plan: RidePlan; data: GenerateRouteResponse }> {
  mkdirSync(CACHE, { recursive: true });
  const file = `${CACHE}/${spec.id}.json`;
  if (existsSync(file)) return JSON.parse(readFileSync(file, "utf8"));
  const plan = composeRidePlan({ places: spec.places.map((p) => p.name), tripType: spec.trip, durationMode: "flexible", hours: 4, profile: DEFAULT_PROFILE });
  const t0 = Date.now();
  const res = await fetch(`${BASE}/api/generate-route`, {
    method: "POST", headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ plan, prompt: "", places: spec.places.map((p) => ({ ...p, label: p.name })) }),
  });
  const data = (await res.json()) as GenerateRouteResponse;
  if (!res.ok || !data.routes?.length) throw new Error(`generate ${spec.id}: ${res.status} ${JSON.stringify(data).slice(0, 300)}`);
  console.log(`generated ${spec.id} in ${Date.now() - t0} ms`);
  writeFileSync(file, JSON.stringify({ plan, data }));
  return { plan, data };
}

type Routed = { runs: RoutedRun[] };
async function reroute(plan: RidePlan, places: RidePlaces, runs: EditRun[]): Promise<Routed | { status: number; body: string }> {
  const res = await fetch(`${BASE}/api/reroute-leg`, {
    method: "POST", headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      plan: planWithPlaces(plan, places),
      runs: runs.map((run) => run.points.map(([lon, lat]) => ({ lat, lon }))),
      loops: runs.map((run) => run.points.length >= 3),
      shapes: runs.map((run) => shapeFlags(run, places)),
    }),
  });
  return res.ok ? ((await res.json()) as Routed) : { status: res.status, body: await res.text() };
}

/** Why a splice is unsound, in words: each break's run end, each missed stop's distance. */
function explain(segments: Segs, original: Segs, places: RidePlaces, runs: EditRun[], routed: RoutedRun[]): string[] {
  const out: string[] = [];
  const line = coordinatesOf(segments);
  for (const b of lineBreaks(segments, original)) out.push(`break ${b.meters} m at feature ${b.index}`);
  runs.forEach((run, i) => {
    const got = coordinatesOf(routed[i].segments);
    const a = haversineMeters(run.points[0], got[0]);
    const z = haversineMeters(run.points.at(-1)!, got.at(-1)!);
    if (a > 30 || z > 30) {
      const lc = cumulative(coordinatesOf(original));
      const ol = coordinatesOf(original);
      const na = nearestAlong(got[0], ol, lc), nz = nearestAlong(got.at(-1)!, ol, lc);
      out.push(`run ${i} [${Math.round(run.fromMeters)}–${Math.round(run.toMeters)}, ${run.points.length} pts]: starts ${Math.round(a)} m / ends ${Math.round(z)} m from its cut; start is ${Math.round(na.meters)} m off the old line at ${Math.round(na.alongMeters)}, end ${Math.round(nz.meters)} m off at ${Math.round(nz.alongMeters)}`);
      if (process.env.DEBUG) out.push(`   points ${JSON.stringify(run.points)} got0 ${JSON.stringify(got.slice(0, 3))}`);
    }
  });
  const cum = cumulative(line);
  const anchors = anchorsOf({ ...places, vias: stopsOf(places) }, line.at(-1)!);
  anchors.forEach((p, k) => {
    const n = nearestAlong(p, line, cum);
    if (n.meters > TOL) out.push(`stop ${k} (${k === 0 ? "start" : k === anchors.length - 1 ? "finish" : stopsOf(places)[k - 1]?.name}) ${Math.round(n.meters)} m from the line`);
  });
  if (!out.length) out.push("stops out of order (each within tolerance, not in riding order)");
  return out;
}

async function attempt(label: string, plan: RidePlan, base: Segs, route: GeneratedRoute, before: RidePlaces, after: RidePlaces) {
  const line = coordinatesOf(base);
  const planned = planEdit({ line, cum: cumulative(line), before, after });
  if (!planned || "error" in planned) { console.log(`  ${label}: no plan ${JSON.stringify(planned)}`); return null; }
  const t0 = Date.now();
  const data = await reroute(plan, planned.places, planned.runs);
  if ("status" in data) { console.log(`  ${label}: HTTP ${data.status} ${data.body.slice(0, 120)}`); return { label, first: "http", final: "http" }; }
  const keep = anchorsOf(before, line[line.length - 1]);
  const splice = (runs: EditRun[], r: Routed) => applyRuns({ segments: base, distanceMeters: route.distanceMeters, durationSeconds: route.durationSeconds, runs, routed: r.runs, keep });
  const spliced = splice(planned.runs, data);
  const v1 = spliceIsSound({ segments: spliced.segments, original: base, places: planned.places, before, toleranceMeters: TOL });
  let final: string = v1.ok ? "ok" : "broken";
  let why: string[] = [];
  let whyAgain: string[] = [];
  let outcome = spliced;
  if (!v1.ok) {
    why = explain(spliced.segments, base, planned.places, planned.runs, data.runs);
    const span = spanRun({ line, cum: cumulative(line), before, after: planned.places, runs: planned.runs });
    const again = await reroute(plan, planned.places, [span]);
    if ("status" in again) { final = `broken (retry HTTP ${again.status})`; }
    else {
      const whole = splice([span], again);
      const v2 = spliceIsSound({ segments: whole.segments, original: base, places: planned.places, before, toleranceMeters: TOL });
      if (v2.ok) { final = "ok after retry"; outcome = whole; }
      else if (!v1.ok && v1.offRoadMeters) { final = `off-road ${v1.offRoadMeters} m (said so)`; }
      else { final = "REFUSED"; whyAgain = explain(whole.segments, base, planned.places, [span], again.runs); }
    }
  }
  // What the page does next with a sound line: a changed place past 500 m is refused as off-road.
  if (final === "ok" || final === "ok after retry") {
    const snapped = snapToLine({ line: outcome.coordinates, before, after: planned.places, maxMoveMeters: TOL });
    if ("error" in snapped) final = `off-road ${snapped.meters} m`;
  }
  const km = (m: number) => (m / 1000).toFixed(1);
  console.log(`  ${label.padEnd(30)} ${planned.kind.padEnd(11)} runs ${planned.runs.length} → ${final.padEnd(15)} ${km(route.distanceMeters)} → ${km(outcome.distanceMeters)} km  ${Date.now() - t0} ms`);
  for (const w of why) console.log(`      first: ${w}`);
  for (const w of whyAgain) console.log(`      retry: ${w}`);
  return { label, first: v1.ok ? "ok" : "broken", final, outcome, places: planned.places };
}

const offset = (p: Point, north: number, east: number): Point => [p[0] + east / (111195 * Math.cos((p[1] * Math.PI) / 180)), p[1] + north / 111195];

async function main() {
  const tally: { ride: string; label: string; first: string; final: string }[] = [];
  for (const spec of RIDES) {
    const { plan, data } = await ride(spec);
    const route = data.routes[0];
    const places = placesFromRide({ plan, start: data.start, via: data.via ?? [], destination: data.destination ?? null, picked: spec.places.map((p) => ({ ...p, label: p.name })) });
    const base = route.segments;
    const line = coordinatesOf(base);
    const cum = cumulative(line);
    const total = cum.at(-1)!;
    console.log(`${spec.id}: ${(total / 1000).toFixed(1)} km, ${stopsOf(places).length} stops, variant ${route.variant}`);
    const run = async (label: string, after: RidePlaces | { error: string }) => {
      if ("error" in after) { console.log(`  ${label}: ${after.error}`); return; }
      const r = await attempt(label, plan, base, route, places, after);
      if (r) tally.push({ ride: spec.id, label, first: r.first, final: r.final });
    };
    const stops = stopsOf(places);
    // 1. drag stop 1 by ~300 m sideways.
    if (stops[0]) {
      const moved = offset([stops[0].lon, stops[0].lat], 220, 220);
      await run("drag stop 1 300 m", { ...places, vias: places.vias.map((v) => (v === stops[0] ? { ...v, lat: moved[1], lon: moved[0] } : v)) });
    }
    // 2. a new stop 120 m beside the line at 35 %.
    const at35 = offset(pointAtDistance(line, cum, total * 0.35).point, 120, 0);
    const newStop = { name: "Jauna pietura", label: "Jauna pietura", lat: at35[1], lon: at35[0] };
    await run("add stop at 35 %", insertStopsByAlong(line, places, [newStop]));
    // 3. a sight 400 m off the line at 60 %.
    const at60 = offset(pointAtDistance(line, cum, total * 0.6).point, -300, 260);
    await run("add sight 400 m off at 60 %", insertStopsByAlong(line, places, [{ name: "Apskates vieta", label: "Apskates vieta", lat: at60[1], lon: at60[0] }]));
    // 4. a batch of two at 20 % and 75 %.
    const b1 = offset(pointAtDistance(line, cum, total * 0.2).point, 80, 80);
    const b2 = offset(pointAtDistance(line, cum, total * 0.75).point, -80, 80);
    await run("batch of two", insertStopsByAlong(line, places, [
      { name: "Partija 1", label: "Partija 1", lat: b1[1], lon: b1[0] },
      { name: "Partija 2", label: "Partija 2", lat: b2[1], lon: b2[0] },
    ]));
    // 5. hold-drag the line at 50 % by 400 m.
    const grab = pointAtDistance(line, cum, total * 0.5).point;
    const bent = offset(grab, 300, -260);
    await run("bend line at 50 %", applyShapeEdit(places, { kind: "add", lat: bent[1], lon: bent[0], grabbedAt: grab }));
    // 6. Izņemt the last stop.
    if (stops.length) await run("remove last stop", { ...places, vias: places.vias.filter((v) => v !== stops.at(-1)) });
    // Taps well off the road network: 700–1500 m off the line.
    for (const [f, n, e] of [[0.25, 900, 300], [0.5, -1200, 0], [0.7, 700, -700]] as const) {
      const q = offset(pointAtDistance(line, cum, total * f).point, n, e);
      await run(`far tap ${Math.round(f * 100)} % ${Math.round(Math.hypot(n, e))} m`, insertStopsByAlong(line, places, [{ name: "Tālu", label: "Tālu", lat: q[1], lon: q[0] }]));
    }
    // A seeded sweep of taps, drags and bends anywhere on the ride.
    let seed = 7;
    const rnd = () => ((seed = (seed * 1103515245 + 12345) % 2147483648) / 2147483648);
    for (let k = 0; k < SWEEP; k++) {
      const f = 0.05 + rnd() * 0.9;
      const p = pointAtDistance(line, cum, total * f).point;
      const dist = 40 + rnd() * 360, ang = rnd() * 2 * Math.PI;
      const q = offset(p, dist * Math.cos(ang), dist * Math.sin(ang));
      const kind = k % 3;
      if (kind === 0) await run(`tap stop ${Math.round(f * 100)} % ${Math.round(dist)} m`, insertStopsByAlong(line, places, [{ name: `S${k}`, label: `S${k}`, lat: q[1], lon: q[0] }]));
      else if (kind === 1) await run(`bend ${Math.round(f * 100)} % ${Math.round(dist)} m`, applyShapeEdit(places, { kind: "add", lat: q[1], lon: q[0], grabbedAt: p }));
      else if (stops.length) {
        const s0 = stops[k % stops.length];
        const m = offset([s0.lon, s0.lat], dist * Math.cos(ang), dist * Math.sin(ang));
        await run(`drag stop ${(k % stops.length) + 1} ${Math.round(dist)} m`, { ...places, vias: places.vias.map((v) => (v === s0 ? { ...v, lat: m[1], lon: m[0] } : v)) });
      }
    }
  }
  const refused = tally.filter((t) => t.final === "REFUSED").length;
  const broken = tally.filter((t) => t.first === "broken").length;
  const offRoad = tally.filter((t) => t.final.startsWith("off-road")).length;
  console.log(`\n${tally.length} edits: first splice broken ${broken}, refused as broken line ${refused}, refused as off-road ${offRoad}`);
}
main().catch((e) => { console.error(e); process.exit(1); });
